// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpnekpqeybyhzhcncdst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwbmVrcHFleWJ5aHpoY25jZHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjIzMDIsImV4cCI6MjA1NzYzODMwMn0.qrhi_QSnYEsCo_OQEnKQ4w6dLOuI42XqrMf__rP7qcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);